### ISSUE TITLE
error subjack

### ISSUE THREAD

**Issue by oldesec** [haccer/subjack#34]
Hi

I often see the following error.

Sorry, I do not know how to reproduce.

```
        /usr/local/go/src/encoding/json/decode.go:371 +0xff
encoding/json.(*decodeState).object(0xc018224960, 0x98c280, 0xc018282fc8, 0x199, 0xc018224988, 0x7b)
        /usr/local/go/src/encoding/json/decode.go:763 +0x1899
encoding/json.(*decodeState).value(0xc018224960, 0x98c280, 0xc018282fc8, 0x199, 0x98c280, 0xc018282fc8)
        /usr/local/go/src/encoding/json/decode.go:381 +0x6e
encoding/json.(*decodeState).array(0xc018224960, 0x9237a0, 0xc018275f80, 0x16, 0xc018224988, 0x5b)
        /usr/local/go/src/encoding/json/decode.go:560 +0x1ae
encoding/json.(*decodeState).value(0xc018224960, 0x9237a0, 0xc018275f80, 0x16, 0xc0243a3e00, 0x8bedbc)
        /usr/local/go/src/encoding/json/decode.go:371 +0xff
encoding/json.(*decodeState).unmarshal(0xc018224960, 0x9237a0, 0xc018275f80, 0xc018224988, 0x0)
        /usr/local/go/src/encoding/json/decode.go:179 +0x1fe
encoding/json.Unmarshal(0xc01827b300, 0x16bf, 0x18bf, 0x9237a0, 0xc018275f80, 0x0, 0x0)
        /usr/local/go/src/encoding/json/decode.go:106 +0x123
github.com/haccer/subjack/subjack.fingerprints(0x7ffc147a1252, 0x37, 0xc01826f000, 0xc000082fb8, 0x2a)
        /root/go/src/github.com/haccer/subjack/subjack/file.go:118 +0xf3
github.com/haccer/subjack/subjack.(*Subdomain).dns(0xc017cd2480, 0xc00006a4e0)
        /root/go/src/github.com/haccer/subjack/subjack/dns.go:13 +0x4d
github.com/haccer/subjack/subjack.Process.func1(0xc00006a540, 0xc00006a4e0, 0xc000026150)
        /root/go/src/github.com/haccer/subjack/subjack/subjack.go:39 +0x49
created by github.com/haccer/subjack/subjack.Process
        /root/go/src/github.com/haccer/subjack/subjack/subjack.go:37 +0x148

goroutine 28 [runnable]:
reflect.Copy(0x92ff60, 0xc017f5dee0, 0x97, 0x92ff60, 0xc017f5d700, 0x197, 0x97)
        /usr/local/go/src/reflect/value.go:1987 +0x42e
encoding/json.(*decodeState).array(0xc017f680a0, 0x9237a0, 0xc017f5d700, 0x16, 0xc017f680c8, 0x5b)
        /usr/local/go/src/encoding/json/decode.go:550 +0x763
encoding/json.(*decodeState).value(0xc017f680a0, 0x9237a0, 0xc017f5d700, 0x16, 0xc024381e00, 0x8bedbc)
        /usr/local/go/src/encoding/json/decode.go:371 +0xff
encoding/json.(*decodeState).unmarshal(0xc017f680a0, 0x9237a0, 0xc017f5d700, 0xc017f680c8, 0x0)
        /usr/local/go/src/encoding/json/decode.go:179 +0x1fe
encoding/json.Unmarshal(0xc017f61980, 0x16bf, 0x18bf, 0x9237a0, 0xc017f5d700, 0x0, 0x0)
        /usr/local/go/src/encoding/json/decode.go:106 +0x123
github.com/haccer/subjack/subjack.fingerprints(0x7ffc147a1252, 0x37, 0xc017f3b400, 0xc000082c18, 0x2a)
        /root/go/src/github.com/haccer/subjack/subjack/file.go:118 +0xf3
github.com/haccer/subjack/subjack.(*Subdomain).dns(0xc017952660, 0xc00006a4e0)
        /root/go/src/github.com/haccer/subjack/subjack/dns.go:13 +0x4d
github.com/haccer/subjack/subjack.Process.func1(0xc00006a540, 0xc00006a4e0, 0xc000026150)
        /root/go/src/github.com/haccer/subjack/subjack/subjack.go:39 +0x49
created by github.com/haccer/subjack/subjack.Process
        /root/go/src/github.com/haccer/subjack/subjack/subjack.go:37 +0x148
```

**Comment by haccer** [comment]
Hi @oldesec - Unfortunately, I can't proceed with fixing this without knowing how to reproduce it.
