### ISSUE TITLE
Subjack not working in VPS with 1gb Memory 

### ISSUE THREAD

**Issue by ethicalhackingplayground** [haccer/subjack#57]
I get this error when installing subjack in my digital ocean box.

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xe44a39, 0x16)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc024000000, 0x4000000, 0x15c6958)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x159e940, 0x2000, 0x2000, 0x7ffed7bea668)
        /usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x159e940, 0x1, 0xffffffff)
        /usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x159e940, 0x1, 0x15c6968, 0x7fcaac69d5f8)
        /usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x159e940, 0x1, 0x15c001c, 0x7fcaac69d5f8)
        /usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.systemstack(0x45a4e4)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc01564cca0 sp=0xc01564cc98 pc=0x45a5e0
runtime.(*mheap).alloc(0x159e940, 0x1, 0x1001c, 0x0)
        /usr/local/go/src/runtime/mheap.go:1092 +0x8a fp=0xc01564ccf0 sp=0xc01564cca0 pc=0x42502a
runtime.(*mcentral).grow(0x159f3f8, 0x0)
        /usr/local/go/src/runtime/mcentral.go:255 +0x7b fp=0xc01564cd30 sp=0xc01564ccf0 pc=0x416f7b
runtime.(*mcentral).cacheSpan(0x159f3f8, 0x203008)
        /usr/local/go/src/runtime/mcentral.go:106 +0x2fe fp=0xc01564cd90 sp=0xc01564cd30 pc=0x416a9e
runtime.(*mcache).refill(0x7fcab01c8008, 0x1c)
        /usr/local/go/src/runtime/mcache.go:138 +0x85 fp=0xc01564cdb0 sp=0xc01564cd90 pc=0x416545
runtime.(*mcache).nextFree(0x7fcab01c8008, 0x1c, 0xc8, 0xe25900, 0xdb9d01)
        /usr/local/go/src/runtime/malloc.go:854 +0x87 fp=0xc01564cde8 sp=0xc01564cdb0 pc=0x40b797
runtime.mallocgc(0xd0, 0xe25900, 0x1, 0xc023fff5f0)
        /usr/local/go/src/runtime/malloc.go:1022 +0x793 fp=0xc01564ce88 sp=0xc01564cde8 pc=0x40c0d3
runtime.newobject(0xe25900, 0xc023fff5f0)
        /usr/local/go/src/runtime/malloc.go:1151 +0x38 fp=0xc01564ceb8 sp=0xc01564ce88 pc=0x40c4c8
cmd/compile/internal/gc.(*Progs).NewProg(...)
        /usr/local/go/src/cmd/compile/internal/gc/gsubr.go:84
cmd/compile/internal/gc.(*Progs).Prog(0xc00a23f650, 0xc023d51983, 0xc023fff520)
        /usr/local/go/src/cmd/compile/internal/gc/gsubr.go:129 +0x2cc fp=0xc01564cf10 sp=0xc01564ceb8 pc=0xc2696c
cmd/compile/internal/gc.(*SSAGenState).Prog(0xc002284f00, 0xc023981983, 0xc023fff520)
        /usr/local/go/src/cmd/compile/internal/gc/ssa.go:5169 +0x3c fp=0xc01564cf38 sp=0xc01564cf10 pc=0xcd29cc
cmd/compile/internal/gc.(*SSAGenState).Br(0xc002284f00, 0x311983, 0xc009b69e60, 0xc023fff520)
        /usr/local/go/src/cmd/compile/internal/gc/ssa.go:5198 +0x39 fp=0xc01564cf90 sp=0xc01564cf38 pc=0xcd2af9
cmd/compile/internal/amd64.ssaGenBlock(0xc002284f00, 0xc009b6a480, 0xc009b6a000)
        /usr/local/go/src/cmd/compile/internal/amd64/ssa.go:1236 +0x1c2 fp=0xc01564d038 sp=0xc01564cf90 pc=0xd4ee72
cmd/compile/internal/gc.genssa(0xc002ccc580, 0xc00a23f650)
        /usr/local/go/src/cmd/compile/internal/gc/ssa.go:5422 +0xde0 fp=0xc01564d510 sp=0xc01564d038 pc=0xcd4080
cmd/compile/internal/gc.compileSSA(0xc002ccd080, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:308 +0x3c2 fp=0xc01564d5f8 sp=0xc01564d510 pc=0xc71de2
cmd/compile/internal/gc.compile(0xc002ccd080)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:277 +0x33d fp=0xc01564d670 sp=0xc01564d5f8 pc=0xc719ad
cmd/compile/internal/gc.funccompile(0xc002ccd080)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:222 +0xc1 fp=0xc01564d6c8 sp=0xc01564d670 pc=0xc71561
cmd/compile/internal/gc.fninit(0xc00029d760, 0x2c, 0x2c)
        /usr/local/go/src/cmd/compile/internal/gc/init.go:63 +0x4a8 fp=0xc01564d7e8 sp=0xc01564d6c8 pc=0xc36c88
cmd/compile/internal/gc.Main(0xe5bfe8)
        /usr/local/go/src/cmd/compile/internal/gc/main.go:692 +0x394b fp=0xc01564dee8 sp=0xc01564d7e8 pc=0xc49a4b
main.main()
        /usr/local/go/src/cmd/compile/main.go:51 +0xac fp=0xc01564df60 sp=0xc01564dee8 pc=0xd8019c
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc01564dfe0 sp=0xc01564df60 pc=0x42f57e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc01564dfe8 sp=0xc01564dfe0 pc=0x45c531
```

**Comment by ethicalhackingplayground** [comment]
It stops installing at zonedb

**Comment by VitaliDzemidovich** [comment]
Same for me: unable to install on 1GB droplet.
But on 2GB it works fine.

**Comment by haccer** [comment]
This is an actual issue, and I think it has something to do with zonedb being very large. I've have to update https://github.com/haccer/available or find another way

**Comment by ethicalhackingplayground** [comment]
Just an idea: you could spin up a very small container and write a small utility tool that uses [https://github.com/zonedb/zonedb](https://github.com/zonedb/zonedb) alongside some performance analysis. Upload the profiles to [https://flamegraph.com/](https://flamegraph.com/) and see where the bottlenecks are.

It could possibly be related to JSON deserialisation, or the way the large file is being loaded into memory. Another thing worth checking is whether there is unnecessary allocation happening during parsing or repeated lookups that could be cached. That should give you a clearer picture of where the time is actually being spent before changing anything major. 👍
